# Path to your oh-my-zsh installation.
# export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="random"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to disable command auto-correction.
# DISABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# add custom local fpath dir
fpath=( ${HOME}/.zsh_custom/functions/ $fpath )

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh_custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# source $ZSH/oh-my-zsh.sh
# use antigen instead
source $HOME/.antigen-repo/antigen.zsh

# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=()
plugins=(
	adolfoabegg/browse-commit
	colorize
	common-aliases
	copydir
	copyfile
	cp
	djui/alias-tips
	git
	jira
	jsontools
	mosh
	sudo
	supercrabtree/k
	systemd
	taskwarrior
	tmux
	vagrant
	vi-mode
	web-search
	yum
	zsh_reload
	zsh-users/zsh-syntax-highlighting
)

antigen use oh-my-zsh

for plugin in ${plugins}; do
	antigen bundle ${plugin}
done

antigen apply

antigen theme $( shuf -n1 ~/.zsh_favlist )

if [[ -e $HOME/.zsh_local ]]; then
	source $HOME/.zsh_local # local stuff not to be put in repo.
fi

# User configuration

for file in ${HOME}/.zsh_custom/*.zsh; do
	source $file
done

# set fpath
fpath=($HOME/.zsh_custom/functions $fpath)
if [ -d $HOME/.zsh_local_funcs ]; then
	fpath=($HOME/.zsh_local_funcs $fpath)
fi

# now auto load any functions you can find.
for fdir in ${fpath[@]}; do
	if [[ -d $fdir ]]; then
		autoload $fdir/*(N:t)
	fi
done

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/sbin:/usr/sbin:/home/peteches/.local/bin:/home/peteches/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/peteches/scripts:/home/peteches/bin:/home/peteches/.local/bin:/home/peteches/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
